name: Node.js Package

on:
    push:
        branches:
            - master

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - uses: actions/checkout@v3

            - name: Read node and npm versions from package.json
              uses: skjnldsv/read-package-engines-version-actions@v2
              id: package-engines-versions

            - name: Print node version number
              run: echo "Node version is ${{ steps.package-engines-versions.outputs.nodeVersion }}"

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.package-engines-versions.outputs.nodeVersion }}

            - name: Update npm to the specified version
              run: |
                  npm install -g npm@${{ steps.package-engines-versions.outputs.npmVersion }}
                  npm --version

            - name: Bump package.json version
              run: |
                  # Set username and email address
                  git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
                  git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
                  npm version patch -m "[RELEASE]: %s"
                  git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Mezmeriz/three-ts-types.git

            - name: Install and build
              run: |
                  npm ci
                  npm run build

            - name: Set registry to Github packages
              uses: actions/setup-node@v3
              with:
                  registry-url: https://npm.pkg.github.com/

            - name: Publish
              run: |
                  cd ./build
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
